name: aml-project
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _pytorch_select=0.1
  - absl-py=1.0.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - alsa-lib=1.2.3
  - aom=3.2.0
  - argon2-cffi=20.1.0
  - async-timeout=4.0.2
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.0.0
  - blinker=1.4
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.10.8
  - cachetools=4.2.4
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.9
  - click=8.0.3
  - cryptography=36.0.1
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - dataclasses=0.8
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - efficientnet-pytorch=0.6.3
  - entrypoints=0.3
  - expat=2.4.1
  - ffmpeg=4.4.1
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - frozenlist=1.2.0
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.70.2
  - glib-tools=2.70.2
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=2.3.3
  - google-auth-oauthlib=0.4.6
  - graphite2=1.3.14
  - grpcio=1.38.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - harfbuzz=2.9.1
  - hdf5=1.12.1
  - icu=68.1
  - idna=3.1
  - importlib-metadata=4.8.2
  - importlib_metadata=4.8.2
  - intel-openmp=2021.4.0
  - ipykernel=6.4.1
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jasper=1.900.1
  - jbig=2.1
  - jedi=0.18.0
  - jinja2=3.0.2
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=7.1.0
  - jupyter_console=6.4.0
  - jupyter_core=4.9.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.80.0
  - libdeflate=1.8
  - libdrm=2.4.109
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.70.2
  - libiconv=1.16
  - libidn2=2.3.2
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libnghttp2=1.46.0
  - libnsl=2.0.0
  - libogg=1.3.5
  - libopencv=4.5.3
  - libopus=1.3.1
  - libpciaccess=0.16
  - libpng=1.6.37
  - libpq=13.5
  - libprotobuf=3.18.1
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.3.0
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libuv=1.40.0
  - libva=2.13.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp=1.2.1
  - libwebp-base=1.2.1
  - libxcb=1.14
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzlib=1.2.11
  - llvm-openmp=12.0.1
  - loguru=0.5.3
  - lz4-c=1.9.3
  - markdown=3.3.6
  - markupsafe=2.0.1
  - matplotlib=3.5.0
  - matplotlib-base=3.5.0
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - multidict=5.2.0
  - munch=2.5.0
  - munkres=1.1.4
  - mysql-common=8.0.27
  - mysql-libs=8.0.27
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - nettle=3.7.3
  - ninja=1.10.2
  - notebook=6.4.6
  - nspr=4.32
  - nss=3.73
  - numexpr=2.8.1
  - numpy=1.22.0
  - oauthlib=3.1.1
  - olefile=0.46
  - opencv=4.5.3
  - openh264=2.1.1
  - openssl=1.1.1l
  - packaging=21.3
  - pandas=1.3.4
  - pandocfilters=1.4.3
  - parso=0.8.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.2.4
  - pixman=0.40.0
  - pretrainedmodels=0.7.4
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - protobuf=3.18.1
  - ptyprocess=0.7.0
  - py-opencv=4.5.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pygments=2.10.0
  - pyjwt=2.3.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.9
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.10.0
  - pytorch-mutex=1.0
  - pytz=2021.3
  - pyu2f=0.1.5
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qt=5.12.9
  - qtconsole=5.1.1
  - qtpy=1.10.0
  - readline=8.1
  - requests=2.26.0
  - requests-oauthlib=1.3.0
  - rsa=4.8
  - scipy=1.5.3
  - segmentation-models-pytorch=0.2.1
  - send2trash=1.8.0
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.37.0
  - svt-av1=0.8.7
  - tensorboard=2.7.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.0
  - terminado=0.9.4
  - testpath=0.5.0
  - timm=0.4.12
  - tk=8.6.11
  - torchmetrics=0.6.2
  - torchvision=0.11.1
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.1
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.1
  - wheel=0.37.0
  - widgetsnbextension=3.5.1
  - x264=1!161.3030
  - x265=3.5
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.7.2
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.0
