data:
  resy: 30 # the output of the data loader gets scaled to these dimensions
  resx: 40

  asp_y: 3
  asp_x: 4 # desired aspect ratio; ideally, this matches the aspect ratio of resy/resx

  # exclude_samples: DY7ASN54S9,JANFS05F33
  include_samples: DY7ASN54S9,JANFS05F33 # Overrides exclude_samples
  only_annotated: True # If true, dataloader only loads frames with labels (training only)

  path: data # data folder path (no trailing slash)

# only batch sized used, so far
training:
  optimizer:
    name: ADAM
    lr: 0.00005
    #name: SGD
    #lr: 0.0001

  batch_size: 10
  num_workers: 8