# trainer: hmr
# out_dir: /cluster/scratch/hvaleyre/tmp_out  # NOTE: specify a directory in your scratch directory on Leonhard
# log_comment: two_for_pose_shape_long_run # will appear in log name

data:
  resy: 30
  resx: 40
  # exclude_samples:
  include_samples: DY7ASN54S9,JANFS05F33

  # data folder path (no trailing slash)
  path: data

device: cuda

model:
  name: default

training:
  print_every: 100
  validate_every: 8000
  checkpoint_every: 8000

  optimizer:
    name: ADAM
    lr: 0.00005
    #name: SGD # initial settings
    #lr: 0.0001

  batch_size: 10
  num_workers: 8

loss:
  v2v_l1: True  # loss type
  v2v_l1_w: 0.1  # corresponding weight
